#+STARTUP: showall indent highstars

* Штуки про компиляцию, линкинг и тп

** ELF                                                                 :ELF:

-ELF - не остроухий народец, а Executable and Linkable Format
-Стандартный формат екзекьютабл файлов для Линукса и некоторых других сред,
работой с шарящимеся библиотеками и как формат для объектных файлов
(формируются в результате компиляции кода gcc-шкой) и другого функционала
-В Ельфе содержатся Сегменты и Секции. Могут быть лишь сегменты, могут
быть лишь секции, а может быть все сразу
-Сегменты актуальны лишь при рантайме, а Секции актуальны лишь при
линковке
-Сегменты и секции имеют внутри себя поинтер на начало какого-то участка
памяти и количество байт этого участка памяти. Но, сегменты, в отличие
от секций, еще и указывают где и как данные байты должны быть загружены
на виртуальную/физическую память.
-В эльфе всегда есть ELFHeader - место, где указана метадата, т.е.,
информация об информации в данном файле
-Хедер легко узнать по первым байтам 7f 45 4c 46
-В ельфе хранятся множество разной инфы, например, типы файла

** Executable file

-Один из данных типов - Executable file. Он указывается цифрой 2 в елф
 хедере и запускается как ./exec-name
-Exec файлы не поддерживают ASLR, т.е. он не может быть позиционно
 независимым (он не может быть вброшен в рандомный участок памяти и
 работать как ни в чем не бывало, точка старта всегда будет на одном
 участке памяти при повторных запусках в гдб)
-Поэтому, чтоб заставить работать екзек файл, в современных компиляторах
 нужно указывать -no-pie аргумент, чтобы, компилятор не пытался засунуть
 файл в рандомный участок свободной памяти при запуске.
